export const CREW=[
 {id:'director',name:'Director',initials:'DR',domain:'Story & performance',output:'Treatment, scene intent, performance notes',model:'Connected language model',steps:['State the emotional change in each scene and identify the audience promise.','Write a treatment that keeps the brief, story and character motivation aligned.','Propose blocking and performance direction; attach the script version to every scene.','Publish a treatment version. Other departments can keep their own interpretations.']},
 {id:'dop',name:'DOP',initials:'DP',domain:'Camera & light',output:'Lens language, lighting plans, shot coverage',model:'Connected language model',steps:['Read scene intent and the selected world references before proposing coverage.','Define framing, lens character, camera height, motion and screen direction per shot.','Build a lighting reference for each location and time of day. Preserve motivated shadows.','Create alternative storyboard frames without replacing the director’s current selects.']},
 {id:'design',name:'Production designer',initials:'PD',domain:'Worlds & elements',output:'Location bible, prop sheets, material library',model:'Connected language model',steps:['Extract the environments and practical elements named in the script. Flag assumptions separately.','Define a world bible: scale, geography, surfaces, palette and period.','Make reusable environment plates and prop turnarounds with stable element IDs.','Publish selected reference versions; notify downstream shots when a world reference changes.']},
 {id:'costume',name:'Costume stylist',initials:'CS',domain:'Wardrobe & silhouette',output:'Character looks, fabric and continuity sheets',model:'Connected language model',steps:['Read each character’s scene context and separate identity from wardrobe variations.','Define silhouette, garment layers, fabric, accessories and movement for every look.','Create front, profile and rear reference views plus close-ups for material detail.','Track looks by story day. Flag discrepancies without blocking other departments.']},
 {id:'editor',name:'Editor',initials:'ED',domain:'Pacing & assembly',output:'Animatics, selects, cutdowns, EDL',model:'Connected language model',steps:['Build a paper edit from the script beats and proposed shot coverage.','Create a still-frame animatic with frame-based timing and a separate scratch track.','Compare take alternatives while keeping source lineage and current selects intact.','Package a V1 cut list with source filenames, frame rate and delivery notes.']},
 {id:'producer',name:'Producer',initials:'PR',domain:'Schedule & resources',output:'Production breakdown, dependencies and delivery plan',model:'Connected language model',steps:['Break the actual brief and script into deliverables, resources and production dependencies.','Make a practical schedule with assumptions, blockers and scope alternatives explicitly labeled.','Identify footage, music, rights, assets and crew decisions required for each deliverable.','Prepare a handoff with owners, priorities and cost-control options. Never invent bookings, quotes, approvals or completed renders.']},
 {id:'continuity',name:'Continuity supervisor',initials:'SS',domain:'Continuity & context',output:'Reference diffs, conflicts, continuity notes',model:'Connected language model',steps:['Compare the script version and reference versions bound to each proposed take.','Check identity, wardrobe, props, screen direction, light and scene chronology.','Attach an evidence-based note to each mismatch and name the affected shots.','Never silently update or rerender downstream work. Let its owner adopt the revised reference.']},
] as const;
export { parseScreenplay as parseScript } from './screenplay';
export type { ScriptScene } from './screenplay';
