import { test, expect, type Locator, type Page } from "@playwright/test";
import { createClient } from "@libsql/client";
import { randomUUID } from "node:crypto";
import { signInLocally, localPlatformDbUrl } from "./helpers/workbenchLocal";
import { newProject, type CanvasNode, type Project } from "../lib/workbench/studio";

/**
 * A Rig take whose paid reply was lost, then the shot is edited, then the page
 * is reloaded and Generate pressed again. What becomes of the lost request is
 * read from the server's own record of its Idempotency-Key, never guessed:
 *
 *  - it never reached the server: it is never sent again. Asking fences its key,
 *    so it cannot land later either. The shot as it is now is what goes, quoted
 *    and held to the price on the button, and billed once;
 *  - it reached the server and only the reply was dropped: that job is followed
 *    and nothing is sent. The edited shot is generated by the next press, at the
 *    price on the button.
 *
 * Never both, never neither. Real local routes against an ENGINE_MOCK server;
 * the network is intercepted only to lose a request or its reply, and to cut off
 * the check once. Nothing is billed for real.
 */

const ENGINE = "dreamina-seedance-2-5-260628";
const SHOT = "lost-a";
const BEFORE = "Wide. Hold still on the empty harbour.";
const AFTER = "Close on her hands. She lets go of the rope.";

/* Test fixtures only. */
function shot(id: string, title: string, note: string): CanvasNode {
  return {
    id, title, type: "scene", x: 100, y: 100, width: 344, linked: [], role: "Director", status: "draft", mode: "Video",
    operations: [{ id: `op-${id}`, kind: "direction", enabled: true, values: { note } }],
    engine: ENGINE, durationS: 5, ratio: "16:9", resolution: "720p",
  };
}

type Sent = { path: string; key: string | undefined; body: Record<string, unknown> };

async function seeded(page: Page) {
  const signed = await signInLocally(page.request);
  const me = await page.request.get("/api/me").then((r) => r.json());
  const scope = `particl-active-${me.workspace.id}-${me.id}`;
  const platform = createClient({ url: localPlatformDbUrl(), timeout: 10_000 });
  let tenantUrl: string;
  try {
    await platform.execute({
      sql: "INSERT INTO credit_grants(id,workspace_id,credits,note,kind,created_by,created_at) VALUES(?,?,?,?,?,?,?)",
      args: [randomUUID(), signed.workspace.id, 2000, "Local mock Rig fixture", "admin", "test", Date.now()],
    });
    tenantUrl = String((await platform.execute({ sql: "SELECT db_url FROM workspaces WHERE id=?", args: [signed.workspace.id] })).rows[0].db_url);
  } finally {
    platform.close();
  }
  const project: Project = { ...newProject(`Lost reply ${randomUUID().slice(0, 6)}`), nodes: [shot(SHOT, "Opening wide", BEFORE)] };
  const saved = await page.request.put("/api/workbench/projects", { headers: { "X-Workbench-Scope": scope }, data: { project, revision: 0 } });
  expect(saved.ok(), await saved.text()).toBeTruthy();
  await page.addInitScript(({ scope, id }) => localStorage.setItem(scope, id), { scope, id: project.id });
  const sent: Sent[] = [];
  page.on("request", (request) => {
    const path = new URL(request.url()).pathname;
    if (request.method() === "POST" && path.startsWith("/api/generate")) sent.push({ path, key: request.headers()["idempotency-key"], body: request.postDataJSON() });
  });
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  return { project, scope, tenantUrl, workspaceId: signed.workspace.id, sent, errors };
}

/** The shot's Inspector, open on Controls (a sheet over the list on a phone, opened again if it closed). */
async function inspector(page: Page): Promise<Locator> {
  const body = page.locator(`[data-inspector-body="shot"][data-shot-id="${SHOT}"]`);
  await expect(async () => {
    if (!(await body.isVisible())) await page.getByTestId("toggle-inspector").click();
    await expect(body).toBeVisible({ timeout: 2_000 });
  }).toPass({ timeout: 30_000 });
  await body.getByRole("group", { name: "Inspector tabs" }).getByRole("button", { name: /Controls/ }).click();
  return body;
}

/** The Rig on the Suites (the site on every device), the shot priced and selected. */
async function openShot(page: Page, project: Project): Promise<Locator> {
  await page.goto(`/suites?suite=studio&page=rig&project=${project.id}`);
  const row = page.getByTestId("rig-list").locator(`.pxw-rig-row[data-shot-id="${SHOT}"]`);
  await expect(row).toHaveAttribute("data-status", "ready", { timeout: 60_000 });
  await row.click();
  return inspector(page);
}

/** Press the shot's own Generate, its Inspector open. */
async function press(page: Page) {
  await (await inspector(page)).locator(".pxw-insp-generate").click();
}

/** The exact live quote on the shot's Generate button, once it is ready to press. */
async function priceOn(body: Locator): Promise<number> {
  const button = body.locator(".pxw-insp-generate");
  await expect(button).toHaveText(/^Generate take · \d[\d,]* cr$/, { timeout: 60_000 });
  await expect(button).toBeEnabled();
  return Number((await button.textContent())!.replace(/.*· /, "").replace(/\D/g, ""));
}

const CLAIMS = "particl:pending-generation:";
/** This shot's claimed attempt in the browser's recovery storage, if any. */
const claimOf = (page: Page, project: Project) =>
  page.evaluate(({ prefix, projectId, shotId }) => {
    const key = Object.keys(localStorage).find((k) => k.startsWith(prefix) && k.includes(JSON.stringify(projectId)) && k.endsWith(`${JSON.stringify(shotId)}]`));
    return key ? (JSON.parse(localStorage.getItem(key)!) as { key: string; body: string; credits: number }) : null;
  }, { prefix: CLAIMS, projectId: project.id, shotId: SHOT });

/** Edit the shot after the lost reply: a new note and one step longer, so both the prompt and the price move. */
async function editShot(page: Page, body: Locator, scope: string, project: Project) {
  await body.getByRole("textbox", { name: "Direction note" }).fill(AFTER);
  const before = (await body.getByTestId("shot-duration").textContent())!;
  await body.getByRole("button", { name: "Longer" }).click();
  await expect(body.getByTestId("shot-duration")).not.toHaveText(before);
  const seconds = Number((await body.getByTestId("shot-duration").textContent())!.replace(/\D/g, ""));
  await expect.poll(async () => {
    const saved = await page.request.get(`/api/workbench/projects?id=${project.id}`, { headers: { "X-Workbench-Scope": scope } }).then((r) => r.json()) as { project: Project };
    const node = saved.project.nodes.find((n) => n.id === SHOT);
    return [JSON.stringify(node).includes(AFTER), node?.durationS];
  }, { timeout: 20_000 }).toEqual([true, seconds]);
  return seconds;
}

async function mappedShot(page: Page, scope: string, project: Project) {
  const saved = await page.request.get(`/api/workbench/projects?id=${project.id}`, { headers: { "X-Workbench-Scope": scope } }).then((r) => r.json()) as { project: Project };
  const mapped = saved.project.shotMappings?.[SHOT];
  expect(mapped).toBeTruthy();
  return mapped!;
}

/** Every job this shot has on the server, and every charge the workspace has on the meter. */
async function ledger(tenantUrl: string, workspaceId: string, productionShotId: string) {
  const tenant = createClient({ url: tenantUrl, timeout: 10_000 });
  const platform = createClient({ url: localPlatformDbUrl(), timeout: 10_000 });
  try {
    const jobs = (await tenant.execute({ sql: "SELECT id,prompt,status FROM generations WHERE shot_id=? ORDER BY created_at", args: [productionShotId] })).rows
      .map((r) => ({ id: String(r.id), prompt: String(r.prompt), status: String(r.status) }));
    const charges = (await platform.execute({ sql: "SELECT id,billed_credits FROM meter_events WHERE workspace_id=? ORDER BY created_at", args: [workspaceId] })).rows
      .map((r) => ({ id: String(r.id), credits: Number(r.billed_credits) }));
    return { jobs, charges };
  } finally {
    tenant.close();
    platform.close();
  }
}

/** The ledger once the shot has `jobs` jobs and each is on the meter: admission writes a job's row, then reserves its charge. */
async function settledLedger(tenantUrl: string, workspaceId: string, productionShotId: string, jobs: number) {
  await expect.poll(async () => {
    const books = await ledger(tenantUrl, workspaceId, productionShotId);
    return [books.jobs.length, books.charges.length];
  }, { timeout: 60_000 }).toEqual([jobs, jobs]);
  return ledger(tenantUrl, workspaceId, productionShotId);
}

/** Press Generate once and lose the paid request: before it reaches the server, or after (its reply dropped). */
async function loseFirstTake(page: Page, body: Locator, sent: Sent[], how: "before" | "after") {
  const landed: { id?: string }[] = [];
  let armed = true;
  await page.route("**/api/generate", async (route) => {
    if (!armed || route.request().method() !== "POST") return route.fallback();
    armed = false;
    if (how === "after") landed.push(await (await route.fetch()).json());
    return route.abort(how === "after" ? "connectionreset" : "internetdisconnected");
  });
  const credits = await priceOn(body);
  await press(page);
  await expect.poll(() => sent.filter((s) => s.path === "/api/generate").length, { timeout: 60_000 }).toBe(1);
  /* Refused for now; the claimed attempt stays in recovery storage. */
  await expect(body.locator(".pxw-insp-generate")).toHaveText(/^Generate take · /);
  const first = sent.find((s) => s.path === "/api/generate")!;
  expect(first.body.maxCredits).toBe(credits);
  return { first, credits, landedId: how === "after" ? String(landed[0]?.id ?? "") : null };
}

test("a Rig take that never reached the server is not sent again after the shot is edited: the shot as it is now goes, at the price on the button, billed once", async ({ page }) => {
  test.setTimeout(180_000);
  const { project, scope, tenantUrl, workspaceId, sent, errors } = await seeded(page);
  let body = await openShot(page, project);
  const { first, credits } = await loseFirstTake(page, body, sent, "before");
  const claim = await claimOf(page, project);
  expect(claim?.key).toBe(first.key);
  expect(String(first.body.prompt)).toContain(BEFORE);

  const seconds = await editShot(page, body, scope, project);
  await page.reload();
  body = await openShot(page, project);
  const shown = await priceOn(body);
  expect(shown).not.toBe(credits);
  const mark = sent.length;
  await press(page);

  /* One request goes. What it made and billed is the shot as it is now, at the price on the button — never the stale request. */
  await expect.poll(() => sent.slice(mark).filter((s) => s.path === "/api/generate").length, { timeout: 60_000 }).toBe(1);
  const productionShot = await mappedShot(page, scope, project);
  const { jobs, charges } = await settledLedger(tenantUrl, workspaceId, productionShot, 1);
  const made = (prompt: string) => (prompt.includes(AFTER) ? "the edited shot" : prompt.includes(BEFORE) ? "the stale shot" : prompt);
  expect({ made: made(jobs[0].prompt), billed: charges.map((c) => c.credits) }).toEqual({ made: "the edited shot", billed: [shown] });
  expect(charges[0].id).toBe(jobs[0].id);

  const after = sent.slice(mark);
  const posted = after.find((s) => s.path === "/api/generate")!;
  expect(String(posted.body.prompt)).toContain(AFTER);
  expect(String(posted.body.prompt)).not.toContain(BEFORE);
  expect(posted.body).toMatchObject({ duration: seconds, maxCredits: shown });
  expect(posted.key).not.toBe(first.key);
  /* The server was asked about the lost request first, by its own key. */
  const check = after.findIndex((s) => s.path === "/api/generate/check");
  expect(check).toBeGreaterThanOrEqual(0);
  expect(after[check].body.key).toBe(first.key);
  expect(check).toBeLessThan(after.indexOf(posted));
  await expect(body.locator(".pxw-insp-notice")).toContainText("Your last Generate never reached the server. Nothing was charged for it.");
  await expect.poll(() => claimOf(page, project)).toBeNull();

  /* The stale request can never land later: its key was fenced when it was checked. */
  const late = await page.request.post("/api/generate", {
    headers: { "Content-Type": "application/json", "X-Workbench-Scope": scope, "Idempotency-Key": first.key! },
    data: claim!.body,
  });
  expect(late.status()).toBe(409);
  expect(late.headers()["idempotency-status"]).toBe("complete");
  const books = await ledger(tenantUrl, workspaceId, productionShot);
  expect(books.jobs.map((j) => j.id)).toEqual([jobs[0].id]);
  expect(books.charges.map((c) => c.credits)).toEqual([shown]);
  expect(errors).toEqual([]);
});

test("a Rig take that reached the server with its reply dropped is followed after the shot is edited: nothing is sent, and the next press generates the edit at the price on the button", async ({ page }) => {
  test.setTimeout(240_000);
  const { project, scope, tenantUrl, workspaceId, sent, errors } = await seeded(page);
  let body = await openShot(page, project);
  const { first, credits, landedId } = await loseFirstTake(page, body, sent, "after");
  expect(landedId).toBeTruthy();
  expect((await claimOf(page, project))?.key).toBe(first.key);

  await editShot(page, body, scope, project);
  await page.reload();
  body = await openShot(page, project);
  await priceOn(body);
  const mark = sent.length;
  await press(page);

  /* The server has the request: its job is followed, and nothing is quoted or sent. */
  await expect(body.locator(".pxw-insp-notice")).toContainText("Your last Generate of this shot reached the server", { timeout: 30_000 });
  await expect.poll(() => claimOf(page, project)).toBeNull();
  expect(sent.slice(mark).map((s) => s.path)).toEqual(["/api/generate/check"]);
  expect(sent[mark].body.key).toBe(first.key);
  await expect(page.getByRole("status").filter({ hasText: /Opening wide rendered/ })).toBeVisible({ timeout: 90_000 });
  expect(sent.slice(mark).map((s) => s.path)).toEqual(["/api/generate/check"]);
  const productionShot = await mappedShot(page, scope, project);
  let books = await settledLedger(tenantUrl, workspaceId, productionShot, 1);
  expect(books.jobs.map((j) => j.id)).toEqual([landedId]);
  expect(books.jobs[0].prompt).toContain(BEFORE);
  expect(books.charges.map((c) => c.credits)).toEqual([credits]);

  /* The edit is generated by the next press, through the normal quote and gate, at the price now on the button
     (the filed take is now one of the shot's references, which the live quote includes). */
  const shown = await priceOn(body);
  const again = sent.length;
  await press(page);
  await expect.poll(() => sent.slice(again).filter((s) => s.path === "/api/generate").length, { timeout: 60_000 }).toBe(1);
  expect(sent.slice(again).map((s) => s.path)).toEqual(["/api/generate/quote", "/api/generate"]);
  const posted = sent.slice(again).find((s) => s.path === "/api/generate")!;
  expect(posted.key).not.toBe(first.key);
  expect(String(posted.body.prompt)).toContain(AFTER);
  expect(posted.body.maxCredits).toBe(shown);
  books = await settledLedger(tenantUrl, workspaceId, productionShot, 2);
  expect(books.jobs[1].prompt).toContain(AFTER);
  expect(books.charges.map((c) => c.credits)).toEqual([credits, shown]);
  expect(errors).toEqual([]);
});

test("a lost Rig take whose fate cannot be read yet sends nothing, keeps its claim, and is settled by the next press", async ({ page }) => {
  test.setTimeout(180_000);
  const { project, scope, tenantUrl, workspaceId, sent, errors } = await seeded(page);
  let body = await openShot(page, project);
  const { first } = await loseFirstTake(page, body, sent, "before");
  await editShot(page, body, scope, project);
  await page.reload();
  body = await openShot(page, project);
  const shown = await priceOn(body);

  /* The check itself is cut off: nothing is quoted or sent, and the claim stays for the next press. */
  let cut = true;
  await page.route("**/api/generate/check", (route) => {
    if (!cut) return route.fallback();
    cut = false;
    return route.abort("internetdisconnected");
  });
  const mark = sent.length;
  await press(page);
  await expect(body.locator(".pxw-insp-notice")).toContainText("could not be checked", { timeout: 30_000 });
  expect(sent.slice(mark).map((s) => s.path)).toEqual(["/api/generate/check"]);
  expect((await claimOf(page, project))?.key).toBe(first.key);

  /* The next press reads it (it never arrived), and the edited shot goes once, at the price on the button. */
  expect(await priceOn(body)).toBe(shown);
  const next = sent.length;
  await press(page);
  await expect.poll(() => sent.slice(next).filter((s) => s.path === "/api/generate").length, { timeout: 60_000 }).toBe(1);
  expect(sent.slice(next).map((s) => s.path)).toEqual(["/api/generate/check", "/api/generate/quote", "/api/generate"]);
  const posted = sent.slice(next).find((s) => s.path === "/api/generate")!;
  expect(posted.key).not.toBe(first.key);
  expect(String(posted.body.prompt)).toContain(AFTER);
  expect(posted.body.maxCredits).toBe(shown);
  const productionShot = await mappedShot(page, scope, project);
  const { jobs, charges } = await settledLedger(tenantUrl, workspaceId, productionShot, 1);
  expect(jobs[0].prompt).toContain(AFTER);
  expect(charges.map((c) => c.credits)).toEqual([shown]);
  expect(errors).toEqual([]);
});
