export default function StudioGuide() {
  return <div className="design-review">
    <p className="review-lede">Build a project from the first brief to an editorial handoff.</p>
    <section className="review-section"><h3>Keep the story connected</h3><p>Write the brief and script, build the scene canvas, then bind your look, character and world references to shot nodes. You can edit any stage and keep earlier takes.</p></section>
    <section className="review-section"><h3>Your space and the shared bible</h3><p>Your working space saves privately. Publish selected references and direction to the project bible when collaborators need them. Open a shared project in your own space to develop your version.</p></section>
    <section className="review-section"><h3>Work with Atomik</h3><p>Give Genie a task or select one crew department. Add the relevant context, choose a model and review the credit estimate before running. Activity retains results and failures. Apply a plan to the canvas, then edit its nodes or rerun the affected task.</p><p>Atomik reads project text, supported plain-text uploads and reference metadata. Images, video, audio, PDFs and linked websites are not analyzed.</p></section>
    <section className="review-section"><h3>Generate and keep versions</h3><p>Select a shot or generation node and choose Generate take. Review the engine, references and credit estimate. Results recover through Activity after refresh. If submission is interrupted, Recover submitted take checks the same request. It does not buy a replacement take.</p><p>Crop, grade, transform, mask and mix still images with the node tools. Save a version before a change you may want to reverse. Lock a selected source to keep a later result from replacing it.</p></section>
    <section className="review-section"><h3>Assemble and deliver</h3><p>Add takes to the sequence, set the frame rate and trim in frames. Download the EDL and source package for your editor. The EDL carries straight cuts at 24, 25 or 30 fps; scratch audio is included separately. Source packages are limited to 200 MB. Relink and verify the sequence in your editor before delivery.</p></section>
    <section className="review-section"><h3>Desktop and mobile</h3><p>Use the stages across the top on desktop. On mobile, Workflow opens the same stages, while sheets hold the canvas library, inspector and Atomik. The Particl logo returns Home.</p></section>
  </div>;
}
