'use client';
import {useMemo,useRef} from 'react';
import {ArrowUpRight,GitBranch,Clapperboard,FileText,Upload,Plus,Play,UsersRound,ArrowRight} from 'lucide-react';
import {Button} from '@/components/workbench/ui/button';
import {CREW,parseScript,ScriptScene} from '@/lib/workbench/crew';
import {Project,Shot} from '@/lib/workbench/studio';
import {toast} from 'sonner';

export function CrewPanel({project:p,onRun,onRunAll}:{project:Project;onRun:(role:string)=>void;onRunAll:()=>void}){return <div className="crew-panel"><div className="crew-intro"><UsersRound size={21}/><h3>Your AI production crew</h3><p>One shared story. Choose a department to develop a proposal from the saved brief, script and references.</p><span className="small-tag">One department per request</span></div><Button className="btn primary full-width" onClick={onRunAll}><GitBranch size={15}/>Plan with Genie</Button><div className="crew-cards">{CREW.map(c=>{const count=p.plans.filter(x=>x.role===c.name).length;return <button onClick={()=>onRun(c.id)} className="crew-card" key={c.id}><span className="crew-avatar">{c.initials}</span><span><strong>{c.name}</strong><small>{c.domain}</small><em>{count?`${count} department plan${count===1?'':'s'}`:c.output}</em></span><ArrowUpRight size={14}/></button>})}</div><p className="context-disclosure">Each request runs the selected department through your connected model. Review the proposal and its credit use, then add the useful parts to the production.</p></div>}

export function ScriptPanel({project:p,onScript,onBuild,onCrew}:{project:Project;onScript:(value:string)=>void;onBuild:(scenes:ScriptScene[])=>void;onCrew:()=>void}){const upload=useRef<HTMLInputElement>(null);const scenes=useMemo(()=>parseScript(p.script||''),[p.script]);const cast=[...new Set(scenes.flatMap(s=>s.characters))];return <div className="stage-scroll"><div className="script-topline"><div><span className="eyebrow">FROM PAGE TO PRODUCTION</span><h2>The story is the source.</h2><p>A living script, linked to scenes, people and the world around them.</p></div><Button className="btn" variant="outline" onClick={()=>upload.current?.click()}><Upload size={14}/>Import TXT</Button><input type="file" accept=".txt,.fountain,text/plain" ref={upload} className="hidden" aria-label="Import screenplay text" onChange={async e=>{const file=e.target.files?.[0];if(file){if(file.size>100000){toast.error('Use a script under 100 KB.');return;}onScript(await file.text());toast.success('Script imported');}e.target.value='';}}/></div><div className="script-grid"><div className="script-page"><div className="section-heading"><span><FileText size={15}/>SCREENPLAY</span><span>Editable source</span></div><textarea aria-label="Production screenplay" value={p.script||''} onChange={e=>onScript(e.target.value)} maxLength={100000} spellCheck={false} placeholder={'EXT. LOCATION - DAY\n\nStart with what we see.\n\nCHARACTER\nAnd what we hear.'}/></div><div className="script-breakdown"><div className="section-heading"><h3>Scene breakdown</h3><span className="small-tag">{scenes.length} scenes</span></div><p className="breakdown-note">Live heading extraction · check character cues and scene boundaries. This is a parser, not an AI script analysis.</p><div className="script-stats"><span><strong>{new Set(scenes.map(s=>s.location)).size}</strong>Locations</span><span><strong>{cast.length}</strong>Dialogue cues</span><span><strong>7</strong>AI departments</span></div>{scenes.map((s,i)=><article className="breakdown-scene" key={s.id}><span className="scene-number">{String(i+1).padStart(2,'0')}</span><div><h4>{s.location}</h4><small>{s.time}</small><p>{s.body.slice(0,200)}{s.body.length>200?'…':''}</p>{s.characters.length>0&&<div className="scene-cast">{s.characters.map(c=><span key={c}>{c}</span>)}</div>}</div></article>)}{!scenes.length&&<p className="breakdown-note">Paste a script or import a text screenplay. Standard INT. / EXT. headings become scene cards.</p>}<Button className="btn primary full-width" disabled={!scenes.length} onClick={()=>onBuild(scenes)}><GitBranch size={15}/>Build scene canvas<ArrowUpRight size={14}/></Button><button className="crew-text-link" onClick={onCrew}><UsersRound size={15}/>Bring in the crew<ArrowRight size={14}/></button></div></div></div>}

export function StoryboardPanel({project:p,onEdit,onAsset,onAdd,onField}:{project:Project;onEdit:(shot:Shot)=>void;onAsset:(id:string)=>void;onAdd:()=>void;onField:(shots:Shot[])=>void}){return <div className="stage-scroll"><div className="storyboard-head"><div><span className="eyebrow">THE FILM BEFORE THE FILM</span><h2>Find the frame. Feel the rhythm.</h2><p>Frames, direction and timing. Every card points to a source take.</p></div><Button className="btn primary" onClick={onAdd}><Plus size={15}/>Add frame</Button></div><div className="storyboard-grid">{p.shots.map((s,i)=>{const a=p.assets.find(a=>a.id===s.assetId);return <article className="storyboard-card" key={s.id}><div className="storyboard-number"><span>SHOT {String(i+1).padStart(2,'0')}</span><span>{(s.duration/p.fps).toFixed(1)}s · v{a?.version||1}</span></div><button className="storyboard-image" aria-label={'Open source for '+s.name} onClick={()=>onAsset(s.assetId)}>{a?.kind==='image'?<img src={a.url} alt={a.name}/>:a?.kind==='video'?<video src={a.url} preload="metadata" muted/>:<Clapperboard/>}</button><div className="storyboard-info"><input aria-label={'Shot '+(i+1)+' name'} value={s.name} onChange={e=>onField(p.shots.map(x=>x.id===s.id?{...x,name:e.target.value}:x))}/><textarea aria-label={'Shot '+(i+1)+' direction'} value={s.note} onChange={e=>onField(p.shots.map(x=>x.id===s.id?{...x,note:e.target.value}:x))}/><button onClick={()=>onEdit(s)}><Play size={12}/>Open in sequence<ArrowUpRight size={13}/></button></div></article>})}<button className="upload-tile" onClick={onAdd}><Plus size={26}/><strong>Add a storyboard frame</strong><span>Choose a take from your asset library</span></button></div></div>}
