'use client';
import {ArrowUpRight,GitBranch,Clapperboard,Plus,Play,UsersRound} from 'lucide-react';
import {Button} from '@/components/workbench/ui/button';
import {CREW} from '@/lib/workbench/crew';
import {Project,Shot} from '@/lib/workbench/studio';

export function CrewPanel({project:p,onRun,onRunAll}:{project:Project;onRun:(role:string)=>void;onRunAll:()=>void}){return <div className="crew-panel"><div className="crew-intro"><UsersRound size={21}/><h3>Your AI production crew</h3><p>One shared story. Choose a department to develop a proposal from the saved brief, script and references.</p><span className="small-tag">One department per request</span></div><Button className="btn primary full-width" onClick={onRunAll}><GitBranch size={15}/>Plan with Genie</Button><div className="crew-cards">{CREW.map(c=>{const count=p.plans.filter(x=>x.role===c.name||x.role===c.id).length;return <button onClick={()=>onRun(c.id)} className="crew-card" key={c.id}><span className="crew-avatar">{c.initials}</span><span><strong>{c.name}</strong><small>{c.domain}</small><em>{count?`${count} department plan${count===1?'':'s'}`:c.output}</em></span><ArrowUpRight size={14}/></button>})}</div><p className="context-disclosure">Each request runs the selected department through your connected model. Review the proposal and its credit use, then add the useful parts to the project.</p></div>}

export function StoryboardPanel({project:p,onEdit,onAsset,onAdd,onField}:{project:Project;onEdit:(shot:Shot)=>void;onAsset:(id:string)=>void;onAdd:()=>void;onField:(shots:Shot[])=>void}){return <div className="stage-scroll"><div className="storyboard-head"><div><span className="eyebrow">THE FILM BEFORE THE FILM</span><h2>Find the frame. Feel the rhythm.</h2><p>Frames, direction and timing. Every card points to a source take.</p></div><Button className="btn primary" onClick={onAdd}><Plus size={15}/>Add frame</Button></div><div className="storyboard-grid">{p.shots.map((s,i)=>{const a=p.assets.find(a=>a.id===s.assetId);return <article className="storyboard-card" key={s.id}><div className="storyboard-number"><span>SHOT {String(i+1).padStart(2,'0')}</span><span>{(s.duration/p.fps).toFixed(1)}s · v{a?.version||1}</span></div><button className="storyboard-image" aria-label={'Open source for '+s.name} onClick={()=>onAsset(s.assetId)}>{a?.kind==='image'?<img src={a.url} alt={a.name}/>:a?.kind==='video'?<video src={a.url} preload="metadata" muted/>:<Clapperboard/>}</button><div className="storyboard-info"><input aria-label={'Shot '+(i+1)+' name'} value={s.name} onChange={e=>onField(p.shots.map(x=>x.id===s.id?{...x,name:e.target.value}:x))}/><textarea aria-label={'Shot '+(i+1)+' direction'} value={s.note} onChange={e=>onField(p.shots.map(x=>x.id===s.id?{...x,note:e.target.value}:x))}/><button onClick={()=>onEdit(s)}><Play size={12}/>Open in sequence<ArrowUpRight size={13}/></button></div></article>})}<button className="upload-tile" onClick={onAdd}><Plus size={26}/><strong>Add a storyboard frame</strong><span>Choose a take from your asset library</span></button></div></div>}
