'use client';

import React,{useEffect,useEffectEvent,useRef,useState,useSyncExternalStore} from 'react';
import {ArrowUp,ArrowUpRight,AudioLines,Box,Check,ChevronDown,ChevronRight,Clapperboard,Download,Eye,FileText,Film,GitBranch,Hand,Image as ImageIcon,Layers,LayoutGrid,Lock,Maximize2,Minus,MoreHorizontal,MousePointer2,NotebookPen,Palette,PanelLeftClose,PanelLeftOpen,PanelRightClose,PanelRightOpen,Plus,Power,Search,Settings2,ShieldCheck,SlidersHorizontal,Sparkles,Split,Undo2,Unlock,Upload,UserRound,Workflow,X} from 'lucide-react';
import {Button} from '@/components/workbench/ui/button';
import {Tabs,TabsList,TabsTrigger} from '@/components/workbench/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/workbench/ui/select';
import {Slider} from '@/components/workbench/ui/slider';
import {Checkbox} from '@/components/workbench/ui/checkbox';
import {DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuTrigger} from '@/components/workbench/ui/dropdown-menu';
import {Tooltip,TooltipContent,TooltipTrigger} from '@/components/workbench/ui/tooltip';
import {toast} from 'sonner';
import {Asset,CanvasNode,NodeOperation,NodeType,Project,uid,safeName} from '@/lib/workbench/studio';
import {NODE_DEFS,OP_LABELS,arrangeGraph,canConnect,createNode,generationBrief,generationReferenceIds,hasImageTools,newOperation,nodeHeight,operationsFor,renderNode,resolveAsset} from '@/lib/workbench/node-graph';
import {downloadFile} from '@/lib/workbench/studio-export';
import {uploadWorkbench} from '@/lib/workbench/upload';
import {MobilePanel,useMobileLayout} from './mobile-ui';
import {AssetPreview} from './AssetPreview';

const EMPTY_NODES:CanvasNode[]=[];const EMPTY_ASSETS:Asset[]=[];
const subscribeWindowSize=(update:()=>void)=>{window.addEventListener('resize',update);return()=>window.removeEventListener('resize',update)};
const wideScreen=()=>window.innerWidth>=1100;
const serverWideScreen=()=>true;
const glyphs={brief:FileText,moodboard:Palette,character:UserRound,element:Box,scene:Clapperboard,note:NotebookPen,media:ImageIcon,generate:Sparkles,merge:Layers,grade:SlidersHorizontal,transform:Maximize2,audio:AudioLines,switch:Split,review:ShieldCheck,output:Download};
const opGlyphs={direction:NotebookPen,grade:SlidersHorizontal,transform:Maximize2,mask:Eye,mix:Layers};
function Tool({label,onClick,active=false,disabled=false,children}:{label:string;onClick:()=>void;active?:boolean;disabled?:boolean;children:React.ReactNode}){return <Tooltip><TooltipTrigger asChild><button className={'ng-tool '+(active?'active':'')} type="button" aria-label={label} aria-pressed={active} disabled={disabled} onClick={onClick}>{children}</button></TooltipTrigger><TooltipContent>{label}</TooltipContent></Tooltip>;}
function Pick({label,value,options,onChange,disabled=false}:{label:string;value:string;options:{value:string;label:string}[];onChange:(v:string)=>void;disabled?:boolean}){return <Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label} className="ng-pick"><SelectValue placeholder={label}/></SelectTrigger><SelectContent className="ps">{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;}
function Thumb({asset}:{asset?:Asset}){if(!asset)return <div className="ng-media-empty"><ImageIcon size={24}/><span>Connect a source</span></div>;if(asset.kind==='image'||asset.kind==='video')return <AssetPreview asset={asset}/>;return <div className="ng-media-empty">{asset.kind==='audio'?<AudioLines size={28}/>:<FileText size={28}/>}<span>{asset.name}</span></div>;}

type Props={project:Project;onChange:(fn:(p:Project)=>Project,remember?:boolean)=>void;selectedId:string|null;onSelect:(id:string|null)=>void;onAsset:(id:string)=>void;onSequence:(a:Asset)=>void;onUpload:()=>void;onFiles:(files:File[])=>void;onUndo:()=>void;onCrew:(role?:string)=>void;onDeliver:()=>void;onPublish:()=>void;onGenerate?:(node:CanvasNode,prompt:string,refs:string[])=>Promise<void>|void;generatingNodeId?:string|null;scope:string;requestScope:string;onScope:(v:string)=>void;apiBase:string;};
export default function ProductionGraph({project:p,onChange,selectedId,onSelect,onAsset,onSequence,onUpload,onFiles,onUndo,onCrew,onDeliver,onPublish,onGenerate,generatingNodeId,scope,requestScope,onScope}:Props){
 const mobile=useMobileLayout();const [view,setView]=useState('canvas');
 const pointers=useRef(new Map<number,{x:number;y:number}>());const pinch=useRef<{distance:number;zoom:number;worldX:number;worldY:number}|null>(null);const moved=useRef(false);
 const readonly=scope==='Shared production';const nodes=readonly?(p.sharedNodes||EMPTY_NODES):p.nodes;const assets=readonly?(p.sharedAssets||EMPTY_ASSETS):p.assets;
 const desktopLibrary=useSyncExternalStore(subscribeWindowSize,wideScreen,serverWideScreen);
 const [libraryChoice,setLibrary]=useState<boolean|null>(null),[inspectorChoice,setInspector]=useState<boolean|null>(null),[libraryTab,setLibraryTab]=useState('nodes'),[query,setQuery]=useState('');
 const library=libraryChoice??desktopLibrary,inspector=inspectorChoice??!mobile;
 const [tab,setTab]=useState('tools'),[tool,setTool]=useState('select'),[zoom,setZoom]=useState(.82),[pan,setPan]=useState({x:28,y:30});
 const [wire,setWire]=useState<string|null>(null),[cursor,setCursor]=useState({x:0,y:0}),[draft,setDraft]=useState<{id:string;x:number;y:number}|null>(null);
 const [previewResult,setPreviewResult]=useState<{nodeId:string;url:string;error:string}|null>(null),[renderingNodeId,setRenderingNodeId]=useState<string|null>(null),[saving,setSaving]=useState(false),[compareNodeId,setCompareNodeId]=useState<string|null>(null);
 const preview=previewResult?.nodeId===selectedId?previewResult.url:'',previewError=previewResult?.nodeId===selectedId?previewResult.error:'',rendering=renderingNodeId!==null&&renderingNodeId===selectedId,compare=compareNodeId!==null&&compareNodeId===selectedId;
 const setCompare=(value:boolean)=>setCompareNodeId(value?selectedId:null);
 const [versionName,setVersionName]=useState('');
 const [submittingNode,setSubmittingNode]=useState<string|null>(null);
 async function generateSelected(){if(!node||!mutable||!onGenerate||submittingNode||generatingNodeId)return;setSubmittingNode(node.id);try{if(mobile)setInspector(false);await onGenerate(node,generationBrief(node,p),generationReferenceIds(node,p));}catch(error){toast.error(error instanceof Error?error.message:'The generation could not be submitted.');}finally{setSubmittingNode(null);}}
 const viewport=useRef<HTMLDivElement>(null),audioRef=useRef<HTMLAudioElement>(null),latest=useRef(p);
 useEffect(()=>{latest.current=p},[p]);
 const drag=useRef<{type:'node'|'pan';id?:string;sx:number;sy:number;x:number;y:number;nextX:number;nextY:number}|null>(null);
 const node=nodes.find(n=>n.id===selectedId)||null;const asset=node?resolveAsset(node,nodes,assets):undefined;
 const mutable=!!node&&!readonly&&!node.locked;const visual=!!asset&&asset.kind==='image';
 function showAsset(id:string){if(mobile)setInspector(false);onAsset(id);}
 function openCrew(){if(mobile)setInspector(false);onCrew();}
 function openLibrary(){if(mobile)setInspector(false);setLibrary(true);setLibraryTab('nodes');setQuery('');}
 function focusNode(n:CanvasNode){const width=viewport.current?.clientWidth||(typeof window!=='undefined'?window.innerWidth:390);const height=viewport.current?.clientHeight||420;const z=Math.min(.95,(width-52)/n.width);setZoom(z);setPan({x:(width-n.width*z)/2-n.x*z,y:Math.max(52,(height-nodeHeight(n)*z-76)/2)-n.y*z});}
 function trackPointer(e:React.PointerEvent<HTMLElement>){if(e.pointerType!=='touch')return;pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.current.size===2){const [a,b]=Array.from(pointers.current.values());const box=viewport.current!.getBoundingClientRect();const center={x:(a.x+b.x)/2-box.left,y:(a.y+b.y)/2-box.top};pinch.current={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom,worldX:(center.x-pan.x)/zoom,worldY:(center.y-pan.y)/zoom};drag.current=null;setDraft(null);moved.current=true;for(const id of pointers.current.keys())viewport.current?.setPointerCapture(id);}}
 function movePinch(e:React.PointerEvent<HTMLElement>){if(pointers.current.has(e.pointerId))pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(!pinch.current||pointers.current.size<2)return false;const [a,b]=Array.from(pointers.current.values());const box=viewport.current!.getBoundingClientRect();const next=Math.max(.25,Math.min(1.6,pinch.current.zoom*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,pinch.current.distance)));setZoom(next);setPan({x:(a.x+b.x)/2-box.left-pinch.current.worldX*next,y:(a.y+b.y)/2-box.top-pinch.current.worldY*next});return true;}
 function update(id:string,fields:Partial<CanvasNode>){onChange(old=>({...old,nodes:old.nodes.map(n=>n.id===id?{...n,...fields}:n)}));}
 function fit(items=nodes){if(!items.length){setPan({x:35,y:35});setZoom(.82);return;}const left=Math.min(...items.map(n=>n.x))-35,top=Math.min(...items.map(n=>n.y))-35,right=Math.max(...items.map(n=>n.x+n.width))+35,bottom=Math.max(...items.map(n=>n.y+nodeHeight(n)))+35;const z=Math.max(.25,Math.min(1,(viewport.current?.clientWidth||900)/(right-left),(viewport.current?.clientHeight||600)/(bottom-top)));setZoom(z);setPan({x:-left*z,y:-top*z});}
 function zoomBy(step:number){const next=Math.max(.25,Math.min(1.6,zoom+step));const center={x:(viewport.current?.clientWidth||900)/2,y:(viewport.current?.clientHeight||600)/2};setPan({x:center.x-(center.x-pan.x)*next/zoom,y:center.y-(center.y-pan.y)*next/zoom});setZoom(next);}
 function add(type:NodeType,assetId?:string,position?:{x:number;y:number}){if(readonly){toast('Open My space to add a node.');return;}if(p.nodes.length>=250){toast.error('This canvas has reached its 250-node limit.');return;}const pos=position||{x:Math.max(0,((viewport.current?.clientWidth||900)/2-pan.x)/zoom-130),y:Math.max(0,((viewport.current?.clientHeight||500)/2-pan.y)/zoom-90)};const next=createNode(type,p.nodes.filter(n=>n.type===type).length,pos);if(assetId){next.assetId=assetId;next.title=assets.find(a=>a.id===assetId)?.name||next.title;}onChange(old=>({...old,nodes:[...old.nodes,next]}));onSelect(next.id);setInspector(true);setTab('tools');if(mobile){setLibrary(false);setView('canvas');requestAnimationFrame(()=>focusNode(next));}toast.success(NODE_DEFS[type].label+' added');}
 function addFromLibrary(event:React.MouseEvent<HTMLButtonElement>){const type=event.currentTarget.dataset.nodeType as NodeType;if(type in NODE_DEFS)add(type);}
 function connect(source:string,target:string){if(readonly)return;const err=canConnect(p.nodes,source,target);if(err){toast.error(err);return;}update(target,{linked:[...p.nodes.find(n=>n.id===target)!.linked,source]});setWire(null);toast.success('Nodes connected');}
 function duplicate(n:CanvasNode){if(readonly||p.nodes.length>=250)return;const copy={...structuredClone(n),id:uid('node'),title:n.title+' / copy',x:n.x+40,y:n.y+40,locked:false,versions:[]};onChange(old=>({...old,nodes:[...old.nodes,copy]}));onSelect(copy.id);}
 function remove(n:CanvasNode){if(readonly||n.locked)return;onChange(old=>({...old,nodes:old.nodes.filter(v=>v.id!==n.id).map(v=>({...v,linked:v.linked.filter(id=>id!==n.id),activeInput:v.activeInput===n.id?undefined:v.activeInput}))}));onSelect(null);setWire(null);toast('Node removed. Use Undo to restore it.');}
 function snapshot(){if(!node||!mutable)return;const version={id:uid('version'),label:versionName.trim()||'Version '+((node.versions?.length||0)+1),assetId:node.assetId,text:node.text,operations:structuredClone(operationsFor(node)),savedAt:new Date().toISOString()};update(node.id,{versions:[...(node.versions||[]),version].slice(-30)});setVersionName('');toast.success('Node version saved');}
 function opUpdate(id:string,values:NodeOperation['values']){if(node&&mutable)update(node.id,{operations:operationsFor(node).map(o=>o.id===id?{...o,values:{...o.values,...values}}:o)});}
 function addOp(kind:NodeOperation['kind']){if(node&&mutable){if(operationsFor(node).length>=20){toast('This node can contain up to 20 tools.');return;}update(node.id,{operations:[...operationsFor(node),newOperation(kind)]});}}
 useEffect(()=>{if(!node||!visual)return;let cancelled=false;const timer=setTimeout(()=>{setRenderingNodeId(node.id);void renderNode(compare?{...node,operations:[]}:node,{...p,nodes,assets}).then(canvas=>{if(!cancelled)setPreviewResult({nodeId:node.id,url:canvas.toDataURL('image/png'),error:''});}).catch(err=>{if(!cancelled)setPreviewResult({nodeId:node.id,url:'',error:err instanceof Error?err.message:'Preview unavailable'});}).finally(()=>{if(!cancelled)setRenderingNodeId(null)});},150);return()=>{cancelled=true;clearTimeout(timer)};},[node,p,nodes,assets,compare,visual]);
 useEffect(()=>{if(audioRef.current)audioRef.current.volume=Number(node?.mode||100)/100;},[node?.mode,selectedId]);
 const focusCurrentNode=useEffectEvent(()=>{const current=nodes.find(n=>n.id===selectedId)||nodes[0];if(current)focusNode(current)});
 useEffect(()=>{if(!mobile)return;const frame=requestAnimationFrame(()=>focusCurrentNode());return()=>cancelAnimationFrame(frame)},[mobile,p.id]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,select,[contenteditable], [role="dialog"], [role="menu"], [role="listbox"]'))return;if(e.key==='Escape'){setWire(null);setDraft(null);drag.current=null;}if((e.ctrlKey||e.metaKey)&&e.key==='0'){e.preventDefault();fit();}if(e.key.toLowerCase()==='n'&&!e.ctrlKey&&!e.metaKey){setLibrary(true);setLibraryTab('nodes');}if(e.key.toLowerCase()==='v'&&!e.ctrlKey&&!e.metaKey)setTool('select');if(e.key.toLowerCase()==='h'&&!e.ctrlKey&&!e.metaKey)setTool('pan');if((e.key==='Delete'||e.key==='Backspace')&&node&&mutable){e.preventDefault();remove(node);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);});
 async function saveImage(download=false){if(!node||!visual)return;setSaving(true);try{const canvas=await renderNode(node,{...p,nodes,assets});const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Could not create the image.')),'image/png'));if(download){downloadFile(blob,safeName(node.title)+'.png');return;}const data=await uploadWorkbench(new File([blob],safeName(node.title)+'.png',{type:'image/png'}),undefined,requestScope);if(latest.current.id!==p.id)throw new Error('The production changed. Return to the original production to render this take.');const output:Asset={...asset!,id:data.id,url:data.url,uploadId:data.id,generationId:undefined,mime:'image/png',name:node.title+' / rendered take',version:(asset?.version||0)+1,parentId:asset?.id,status:'Draft',locked:false,category:'Shot',refs:[...new Set([asset!.id,...node.linked.flatMap(id=>{const n=nodes.find(v=>v.id===id);const a=n?resolveAsset(n,nodes,assets):undefined;return a?[a.id]:[];})])],description:'Node render · '+canvas.width+' × '+canvas.height,prompt:generationBrief(node,p)};onChange(old=>({...old,assets:[...old.assets,output]}));toast.success('Rendered take saved in Takes. Your node stack is preserved.');showAsset(output.id);}catch(err){toast.error(err instanceof Error?err.message:'Could not render this node.')}finally{setSaving(false)}}
 const shown=nodes.map(n=>draft?.id===n.id?{...n,x:draft.x,y:draft.y}:n);
 const enabledOps=node?operationsFor(node):[];
 const inputNodes=node?node.linked.map(id=>nodes.find(n=>n.id===id)).filter(Boolean) as CanvasNode[]:[];
 const wireSource=shown.find(n=>n.id===wire);
 const path=(sx:number,sy:number,tx:number,ty:number)=>`M ${sx} ${sy} C ${sx+Math.max(70,Math.abs(tx-sx)*.45)} ${sy}, ${tx-Math.max(70,Math.abs(tx-sx)*.45)} ${ty}, ${tx} ${ty}`;
 return <div className={'node-workbench '+(library?'has-library ':'')+(inspector?'has-inspector ':'')+(view==='list'?'ng-listview':'')}>
  <div className="mobile-node-header"><div className="mobile-node-title"><div><h1>Node studio</h1><span>{nodes.length} nodes · {nodes.reduce((n,v)=>n+v.linked.length,0)} connections</span></div><button className="mobile-add-node" disabled={readonly} onClick={openLibrary} aria-label="Add a node"><Plus size={23}/></button></div><div className="mobile-node-viewbar"><Tabs value={view} onValueChange={value=>{setView(value);if(value==='canvas'&&node)requestAnimationFrame(()=>focusNode(node))}}><TabsList className="mobile-view-tabs"><TabsTrigger value="canvas"><GitBranch size={14}/>Canvas</TabsTrigger><TabsTrigger value="list"><Layers size={14}/>List</TabsTrigger></TabsList></Tabs><div className="mobile-node-space"><Pick label="Canvas space" value={scope} options={[{value:'My space',label:'My space'},{value:'Shared production',label:'Shared view'}]} onChange={onScope}/></div></div></div>
  <div className="ng-commandbar"><div className="ng-command-left"><Tool label={library?'Close node library':'Open node library · N'} active={library} onClick={()=>setLibrary(!library)}>{library?<PanelLeftClose size={17}/>:<PanelLeftOpen size={17}/>}</Tool><span className="ng-command-divider"/><Tabs value={scope} onValueChange={v=>{onScope(v);setWire(null)}}><TabsList className="ng-scope"><TabsTrigger value="My space">My space</TabsTrigger><TabsTrigger value="Shared production">Shared view</TabsTrigger></TabsList></Tabs></div><div className="ng-command-right"><span className="ng-connection-count">{nodes.length} nodes <i/> {nodes.reduce((n,v)=>n+v.linked.length,0)} links</span><Tool label="Arrange by connections" disabled={readonly} onClick={()=>{const next=arrangeGraph(nodes);onChange(old=>({...old,nodes:next}));fit(next)}}><LayoutGrid size={16}/></Tool><Button variant="outline" className="ng-add-button" disabled={readonly} onClick={()=>{setLibrary(true);setLibraryTab('nodes');setQuery('')}}><Plus size={15}/>Add node</Button><Tool label="Publish selected node and inputs to shared view" disabled={readonly||!node} onClick={onPublish}><GitBranch size={16}/></Tool><Tool label={inspector?'Close inspector':'Open inspector'} active={inspector} onClick={()=>setInspector(!inspector)}>{inspector?<PanelRightClose size={17}/>:<PanelRightOpen size={17}/>}</Tool></div></div>
  <div className="ng-desk">
   <MobilePanel mobile={mobile} open={library} onOpenChange={setLibrary} title="Add to canvas" description="Choose a node or bring in source media." kind="library"><aside className="ng-library" aria-label="Node library"><div className="ng-panel-title"><strong>Library</strong><span>15 tools</span><button className="ng-mobile-close" aria-label="Close library" onClick={()=>setLibrary(false)}><X size={17}/></button></div><Tabs value={libraryTab} onValueChange={setLibraryTab}><TabsList className="ng-library-tabs"><TabsTrigger value="nodes">Nodes</TabsTrigger><TabsTrigger value="media">Media <span>{assets.length}</span></TabsTrigger></TabsList></Tabs><div className="ng-search"><Search size={14}/><input aria-label="Search node library" value={query} onChange={e=>setQuery(e.target.value)} placeholder={libraryTab==='nodes'?'Find a node…':'Find an asset…'}/></div><div className="ng-library-list">{libraryTab==='nodes'?(['References','Create','Finish','Flow'] as const).map(family=>{const items=(Object.keys(NODE_DEFS) as NodeType[]).filter(key=>NODE_DEFS[key].family===family&&[NODE_DEFS[key].label,NODE_DEFS[key].description,...NODE_DEFS[key].tools].join(' ').toLowerCase().includes(query.toLowerCase()));return !!items.length&&<div className="ng-library-group" key={family}><h3>{family}<span>{items.length}</span></h3>{items.map(type=>{const Icon=glyphs[type],def=NODE_DEFS[type];return <Tooltip key={type}><TooltipTrigger asChild><button className={'ng-library-item family-'+family.toLowerCase()} disabled={readonly} draggable={!readonly} onDragStart={e=>e.dataTransfer.setData('application/particl-node',type)} data-node-type={type} onClick={addFromLibrary}><span className={'ng-library-glyph shape-'+def.shape}><Icon size={16}/></span><span>{def.label}<small>{def.tools.slice(0,2).join(' · ')}</small></span><Plus size={13}/></button></TooltipTrigger><TooltipContent side="right">{def.description}</TooltipContent></Tooltip>})}</div>}):<div className="ng-media-list">{assets.filter(a=>a.name.toLowerCase().includes(query.toLowerCase())).map(a=><button key={a.id} disabled={readonly} draggable={!readonly} onDragStart={e=>e.dataTransfer.setData('application/particl-asset',a.id)} onClick={()=>add(a.category==='Character'?'character':'media',a.id)}><span><Thumb asset={a}/></span><strong>{a.name}<small>{a.category} · v{a.version}</small></strong><Plus size={13}/></button>)}{!assets.length&&<p>Upload a source to start building.</p>}<Button variant="outline" className="btn full-width" disabled={readonly} onClick={onUpload}><Upload size={15}/>Upload media</Button></div>}</div><div className="ng-library-footer"><MousePointer2 size={13}/><span>Click to add. Drag to place.</span></div></aside></MobilePanel>
   <div className={'ng-canvas '+(tool==='pan'?'ng-pan':'')+(wire?' ng-connecting':'')} ref={viewport} aria-label="Production node canvas" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const box=e.currentTarget.getBoundingClientRect();const pos={x:(e.clientX-box.left-pan.x)/zoom,y:(e.clientY-box.top-pan.y)/zoom};const type=e.dataTransfer.getData('application/particl-node') as NodeType;const aid=e.dataTransfer.getData('application/particl-asset');if(type in NODE_DEFS)add(type,undefined,pos);else if(aid)add('media',aid,pos);else if(e.dataTransfer.files.length&&!readonly)onFiles(Array.from(e.dataTransfer.files));}} onPointerDown={e=>{trackPointer(e);if(pinch.current)return;if((e.target as HTMLElement).closest('button,.ng-node'))return;moved.current=false;drag.current={type:'pan',sx:e.clientX,sy:e.clientY,x:pan.x,y:pan.y,nextX:pan.x,nextY:pan.y};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(movePinch(e))return;const box=e.currentTarget.getBoundingClientRect();setCursor({x:(e.clientX-box.left-pan.x)/zoom,y:(e.clientY-box.top-pan.y)/zoom});const d=drag.current;if(!d)return;const dx=e.clientX-d.sx,dy=e.clientY-d.sy;if(Math.abs(dx)+Math.abs(dy)>5)moved.current=true;d.nextX=d.x+dx/(d.type==='node'?zoom:1);d.nextY=d.y+dy/(d.type==='node'?zoom:1);if(d.type==='pan')setPan({x:d.nextX,y:d.nextY});else setDraft({id:d.id!,x:Math.max(-10000,Math.min(20000,d.nextX)),y:Math.max(-10000,Math.min(20000,d.nextY))});}} onPointerUp={e=>{pointers.current.delete(e.pointerId);if(pinch.current){pinch.current=null;drag.current=null;setDraft(null);return;}const d=drag.current;if(d?.type==='node'&&(d.nextX!==d.x||d.nextY!==d.y))update(d.id!,{x:Math.max(-10000,Math.min(20000,d.nextX)),y:Math.max(-10000,Math.min(20000,d.nextY))});drag.current=null;setDraft(null);const target=(e.target as HTMLElement).closest('[data-input]')?.getAttribute('data-input');if(wire&&target){connect(wire,target);}}} onPointerCancel={e=>{pointers.current.delete(e.pointerId);pinch.current=null;drag.current=null;setDraft(null);setWire(null)}} onWheel={e=>{if(e.ctrlKey||e.metaKey){zoomBy(e.deltaY>0?-.05:.05)}else setPan(old=>({x:old.x-e.deltaX,y:old.y-e.deltaY}));}}>
    <div className="ng-canvas-label"><span><Workflow size={13}/> {p.name} <ChevronRight size={12}/> {readonly?'Shared selection':'Main composition'}</span><span>{readonly?'Snapshot':'NODE GRAPH'}</span></div>
    <div className="ng-world" style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}><svg className="ng-wires" width="5000" height="5000" aria-hidden="true">{shown.flatMap(n=>n.linked.map(id=>{const source=shown.find(a=>a.id===id);if(!source)return null;return <path key={n.id+id} className={n.id===selectedId||source.id===selectedId?'focused':''} d={path(source.x+source.width,source.y+nodeHeight(source)/2,n.x,n.y+nodeHeight(n)/2)}/>;}))}{wireSource&&<path className="ng-draft-wire" d={path(wireSource.x+wireSource.width,wireSource.y+nodeHeight(wireSource)/2,cursor.x,cursor.y)}/>}</svg>
     {shown.map(n=>{const def=NODE_DEFS[n.type],Icon=glyphs[n.type],a=resolveAsset(n,nodes,assets),ops=operationsFor(n);return <article key={n.id} tabIndex={0} aria-label={def.label+' node: '+n.title} className={'ng-node ng-'+def.shape+' ng-type-'+n.type+(n.id===selectedId?' selected':'')+(n.bypassed?' bypassed':'')+(n.collapsed?' collapsed':'')} style={{left:n.x,top:n.y,width:n.width,height:nodeHeight(n)}} onClick={()=>{if(moved.current){moved.current=false;return;}onSelect(n.id);if(mobile)setInspector(true)}} onFocus={()=>onSelect(n.id)} onDoubleClick={()=>{onSelect(n.id);setInspector(true)}} onKeyDown={e=>{if(e.target!==e.currentTarget)return;if(e.key==='Enter'){onSelect(n.id);setInspector(true)}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)&&!readonly&&!n.locked){e.preventDefault();const d=e.shiftKey?40:10;update(n.id,{x:n.x+(e.key==='ArrowLeft'?-d:e.key==='ArrowRight'?d:0),y:n.y+(e.key==='ArrowUp'?-d:e.key==='ArrowDown'?d:0)});}}}>
      <div className="ng-node-header" onPointerDown={e=>{if((e.target as HTMLElement).closest('button')||readonly||n.locked)return;e.stopPropagation();trackPointer(e);if(pinch.current)return;moved.current=false;onSelect(n.id);drag.current={type:tool==='pan'?'pan':'node',id:n.id,sx:e.clientX,sy:e.clientY,x:tool==='pan'?pan.x:n.x,y:tool==='pan'?pan.y:n.y,nextX:tool==='pan'?pan.x:n.x,nextY:tool==='pan'?pan.y:n.y};viewport.current?.setPointerCapture(e.pointerId);}}><span className="ng-node-glyph"><Icon size={16}/></span><span>{n.collapsed?n.title:def.label}</span>{n.locked&&<Lock size={12}/>}<DropdownMenu><DropdownMenuTrigger asChild><button className="ng-node-menu" aria-label={'Actions for '+n.title}><MoreHorizontal size={17}/></button></DropdownMenuTrigger><DropdownMenuContent className="ps"><DropdownMenuItem onClick={()=>{onSelect(n.id);setInspector(true)}}>Open inspector</DropdownMenuItem><DropdownMenuItem disabled={readonly} onClick={()=>duplicate(n)}>Duplicate node</DropdownMenuItem><DropdownMenuItem disabled={readonly||n.locked} onClick={()=>update(n.id,{bypassed:!n.bypassed})}>{n.bypassed?'Enable node':'Bypass node'}</DropdownMenuItem><DropdownMenuItem disabled={readonly} onClick={()=>update(n.id,{collapsed:!n.collapsed})}>{n.collapsed?'Expand node':'Collapse node'}</DropdownMenuItem><DropdownMenuItem disabled={readonly} onClick={()=>update(n.id,{locked:!n.locked})}>{n.locked?'Unlock node':'Lock node'}</DropdownMenuItem><DropdownMenuItem disabled={readonly||n.locked} onClick={()=>remove(n)}>Remove node</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>
      {!n.collapsed&&<>{(def.shape==='reference'||def.shape==='scene')&&<div className="ng-node-visual"><Thumb asset={a}/>{n.type==='character'&&<span className="ng-image-caption">IDENTITY / WARDROBE</span>}{def.shape==='scene'&&<><span className="ng-image-caption">{n.type==='generate'?'GENERATION BRIEF':'SCENE PREVIEW'}</span><button aria-label={'Inspect '+n.title} onClick={()=>{setInspector(true);onSelect(n.id)}}><Maximize2 size={14}/></button></>}</div>}
       {def.shape==='text'?<div className="ng-note-content"><h3>{n.title}</h3><p>{n.text||'Write the intention. Connect it to the work.'}</p></div>:<div className="ng-node-content"><h3>{n.title}</h3>{def.shape==='operator'?<div className="ng-operator-readout">{n.type==='grade'?<><span>B <b>{String(ops.find(o=>o.kind==='grade')?.values.brightness??100)}</b></span><span>C <b>{String(ops.find(o=>o.kind==='grade')?.values.contrast??100)}</b></span><span>S <b>{String(ops.find(o=>o.kind==='grade')?.values.saturation??100)}</b></span></>:n.type==='merge'?<><Layers size={17}/><span>{n.linked.length} inputs</span><b>{String(ops.find(o=>o.kind==='mix')?.values.opacity??50)}%</b></>:n.type==='audio'?<><AudioLines size={22}/><span>{a?.kind==='audio'?'Source attached':'Connect audio'}</span></>:<><Maximize2 size={16}/><span>{String(ops.find(o=>o.kind==='transform')?.values.scale??100)}% scale</span></>}</div>:def.shape==='flow'?<p>{n.type==='review'?(n.status==='approved'?'Approved for the next stage':n.status==='review'?'Review in progress':'Awaiting review'):n.type==='switch'?`${n.linked.length} inputs · ${n.activeInput?'Route selected':'First input active'}`:a?'Result ready to inspect':'Connect a result'}</p>:<p>{n.text||a?.description||def.description}</p>}</div>}
       <div className="ng-node-footer"><span>{n.bypassed?<><Power size={12}/>Bypassed</>:n.status==='approved'?<><Check size={12}/>Approved</>:<>{ops.filter(o=>o.enabled).length>0?<Settings2 size={12}/>:<GitBranch size={12}/>} {ops.length?ops.filter(o=>o.enabled).length+' active tools':n.role||def.role}</>}</span><span>{a?'v'+a.version:String(n.linked.length).padStart(2,'0')+' in'}</span></div>
      </>}
      <button className={'ng-port ng-in '+(wire&&wire!==n.id?'accepting':'')} aria-label={'Connect input to '+n.title} data-input={n.id} disabled={readonly||n.locked} onClick={e=>{e.stopPropagation();if(wire)connect(wire,n.id);else{onSelect(n.id);setInspector(true);setTab('inputs')}}} style={{top:'50%'}}/><button className={'ng-port ng-out '+(wire===n.id?'connecting':'')} aria-label={'Connect output from '+n.title} disabled={readonly} onPointerDown={e=>{e.stopPropagation();const box=viewport.current!.getBoundingClientRect();setCursor({x:(e.clientX-box.left-pan.x)/zoom,y:(e.clientY-box.top-pan.y)/zoom});setWire(n.id);}} onClick={e=>{e.stopPropagation();setWire(n.id)}} style={{top:'50%'}}/>
     </article>})}
    </div>
    {!nodes.length&&<div className="ng-empty"><GitBranch size={36}/><h2>Your next production starts here.</h2><p>Add a brief, a reference or a scene to begin.</p><Button className="btn primary" onClick={()=>readonly?onScope('My space'):add('brief')}>{readonly?'Open my space':'Add a brief'}<Plus size={15}/></Button></div>}
    {wire&&<div className="ng-wire-help">Choose an input port to connect <button onClick={()=>setWire(null)}>Cancel <kbd>Esc</kbd></button></div>}
    {node&&<button className="mobile-selected-node" onClick={()=>setInspector(true)}><span>{React.createElement(glyphs[node.type],{size:19})}</span><span><strong>{node.title}</strong><small>{NODE_DEFS[node.type].label} · {node.linked.length} inputs</small></span><span>Controls<ChevronRight size={17}/></span></button>}
    <div className="ng-canvas-bottom"><div className="ng-zoom"><Tool label="Zoom out" onClick={()=>zoomBy(-.1)}><Minus size={15}/></Tool><button onClick={()=>fit()} aria-label="Fit graph">{Math.round(zoom*100)}%</button><Tool label="Zoom in" onClick={()=>zoomBy(.1)}><Plus size={15}/></Tool><span/><Tool label="Fit all nodes · Ctrl or Command 0" onClick={()=>fit()}><Maximize2 size={15}/></Tool></div><div className="ng-canvas-tools"><Tool label="Select · V" active={tool==='select'} onClick={()=>setTool('select')}><MousePointer2 size={17}/></Tool><Tool label="Pan · H" active={tool==='pan'} onClick={()=>setTool('pan')}><Hand size={17}/></Tool><i/><Tool label="Add direction node" disabled={readonly} onClick={()=>add('note')}><NotebookPen size={17}/></Tool><Tool label="Undo" disabled={readonly} onClick={onUndo}><Undo2 size={16}/></Tool></div><span className="ng-canvas-hint">Connect • Create • Refine</span></div>
   </div>
   <div className="mobile-node-list"><ul>{nodes.map(n=>{const a=resolveAsset(n,nodes,assets);const Icon=glyphs[n.type];return <li key={n.id}><button className={n.id===selectedId?'selected':''} onClick={()=>{onSelect(n.id);setInspector(true)}}><span className={'mobile-node-list-thumb '+(!a?'no-source':'')}>{a&&['image','video'].includes(a.kind)?<Thumb asset={a}/>:<Icon size={24}/>}</span><span className="mobile-node-list-copy"><small><Icon size={12}/>{NODE_DEFS[n.type].label}{n.bypassed?' · Bypassed':''}</small><strong>{n.title}</strong><span>{n.linked.length} inputs · {operationsFor(n).length} tools{n.status==='approved'?' · Approved':''}</span></span><ChevronRight size={19}/></button></li>})}</ul>{!nodes.length&&<p>Add a node to start your production.</p>}<Button variant="outline" className="btn full-width" disabled={readonly} onClick={openLibrary}><Plus size={18}/>Add a node</Button></div>
   <MobilePanel mobile={mobile} open={inspector} onOpenChange={setInspector} title="Node controls" description={node?NODE_DEFS[node.type].label+' · '+node.title:'Select a node on the canvas.'} kind="inspector"><aside className="ng-inspector" aria-label="Node inspector"><div className="ng-panel-title"><strong>Inspector</strong><span>{node?NODE_DEFS[node.type].label:'No selection'}</span><button className="ng-mobile-close" aria-label="Close inspector" onClick={()=>setInspector(false)}><X size={17}/></button></div>{node?<><div className="ng-inspector-identity"><span className="ng-inspector-glyph">{React.createElement(glyphs[node.type],{size:21})}</span><div><input aria-label="Node name" value={node.title} maxLength={300} disabled={!mutable} onChange={e=>update(node.id,{title:e.target.value})}/><small>{node.role||NODE_DEFS[node.type].role}</small></div><Tool label={node.locked?'Unlock node':'Lock node'} disabled={readonly} active={!!node.locked} onClick={()=>update(node.id,{locked:!node.locked})}>{node.locked?<Lock size={15}/>:<Unlock size={15}/>}</Tool></div>
     <div className="ng-monitor"><div className="ng-monitor-label"><span>{compare?'INPUT':'OUTPUT'} <i/> {rendering?'Updating…':node.bypassed?'Bypassed':asset?.kind==='image'?'Still preview':asset?.kind||'No source'}</span><button aria-label="Compare node input" disabled={!visual} className={compare?'active':''} onClick={()=>setCompare(!compare)}><Eye size={14}/>A/B</button></div><div className="ng-monitor-screen">{visual&&preview?<img src={preview} alt={'Output of '+node.title}/>:asset?.kind==='audio'?<div className="ng-audio-player"><AudioLines size={35}/><audio ref={audioRef} controls src={asset.url}/></div>:asset?.kind==='video'?<video src={asset.url} controls playsInline/>:asset?.kind==='document'||asset?.kind==='link'?<div className="ng-media-empty"><FileText size={27}/><a href={asset.url} target="_blank" rel="noreferrer">Open source<ArrowUpRight size={14}/></a></div>:<Thumb asset={asset}/>}</div>{previewError&&<p className="ng-render-error">{previewError}</p>}<div className="ng-monitor-footer"><span>{asset?asset.name:'No media connected'}</span><span>{p.aspect}</span></div></div>
     <Tabs value={tab} onValueChange={setTab}><TabsList className="ng-inspector-tabs"><TabsTrigger value="tools">Controls</TabsTrigger><TabsTrigger value="inputs">Inputs <span>{node.linked.length}</span></TabsTrigger><TabsTrigger value="versions">Versions <span>{node.versions?.length||0}</span></TabsTrigger></TabsList></Tabs>
     <div className="ng-inspector-scroll">
      {tab==='tools'&&<><fieldset disabled={!mutable} className="ng-fieldset"><div className="ng-section-title"><span>NODE SETTINGS</span><button type="button" onClick={()=>update(node.id,{bypassed:!node.bypassed})} className={node.bypassed?'active':''}><Power size={13}/>{node.bypassed?'Enable':'Bypass'}</button></div><label className="ng-label">Department</label><Pick label="Department" value={node.role||NODE_DEFS[node.type].role} options={['Director','DOP','Art director','Costume stylist','VFX artist','Editor','Colourist','Sound designer','Producer'].map(v=>({value:v,label:v}))} onChange={v=>update(node.id,{role:v})}/>
       {(NODE_DEFS[node.type].shape==='text'||['scene','generate','character','moodboard','element','review'].includes(node.type))&&<><label className="ng-label" htmlFor="ng-direction">{node.type==='character'?'Identity & wardrobe':node.type==='review'?'Review notes':'Direction'}</label><textarea id="ng-direction" value={node.text||''} maxLength={30000} placeholder={node.type==='generate'?'Describe the shot, movement and continuity…':'Add the details that matter…'} onChange={e=>update(node.id,{text:e.target.value})}/></>}
       {node.type==='generate'&&<><label className="ng-label">Output intent</label><Pick label="Generation intent" value={node.mode||'Image'} options={['Image','Image edit','Image to video','Video'].map(v=>({value:v,label:v}))} onChange={v=>update(node.id,{mode:v})}/><p className="ng-inline-note">Generate a new take using this direction and the connected reference versions. Progress appears in Atomik Activity.</p><Button className="btn primary full-width" disabled={!onGenerate||!!submittingNode||!!generatingNodeId||!mutable} onClick={()=>void generateSelected()}><Sparkles size={14}/>{submittingNode===node.id?'Submitting…':generatingNodeId===node.id?'Generating…':'Generate take'}</Button><button className="ng-inline-note" type="button" onClick={()=>downloadFile(new Blob([generationBrief(node,p)],{type:'text/plain'}),safeName(node.title)+'-prompt.txt')}>Download direction text</button></>}
       {node.type==='switch'&&<><label className="ng-label">Active input</label><Pick label="Active switch input" value={node.activeInput||node.linked[0]||'none'} options={inputNodes.length?inputNodes.map(n=>({value:n.id,label:n.title})):[{value:'none',label:'Connect an input'}]} onChange={v=>update(node.id,{activeInput:v})}/></>}
       {node.type==='review'&&<><label className="ng-label">Review decision</label><Pick label="Review status" value={node.status||'draft'} options={[{value:'draft',label:'Awaiting review'},{value:'review',label:'Changes requested'},{value:'approved',label:'Approved'}]} onChange={v=>update(node.id,{status:v as CanvasNode['status']})}/></>}
       {node.type==='audio'&&<><div className="ng-range-label"><span>Preview volume</span><output>{node.mode||100}%</output></div><Slider aria-label="Audio preview volume" value={[Number(node.mode||100)]} min={0} max={100} onValueChange={v=>update(node.id,{mode:String(v[0])})}/><p className="ng-inline-note">Volume applies to this preview. The original file is used in the sequence.</p><Button variant="outline" className="btn full-width" disabled={asset?.kind!=='audio'} onClick={()=>{onChange(old=>({...old,audioAssetId:asset!.id}));toast.success('Audio assigned to the sequence')}}><AudioLines size={14}/>Use as soundtrack</Button></>}
       <div className="ng-section-title stack-title"><span>TOOL STACK</span><span>{enabledOps.length} tools</span></div>{!enabledOps.length&&<p className="ng-stack-empty">Add colour, transforms, masks or direction to this node.</p>}
       {enabledOps.map((op,index)=><div className={'ng-operation '+(!op.enabled?'disabled':'')} key={op.id}><div className="ng-operation-title"><Checkbox aria-label={'Enable '+OP_LABELS[op.kind]} checked={op.enabled} onCheckedChange={v=>update(node.id,{operations:enabledOps.map(o=>o.id===op.id?{...o,enabled:!!v}:o)})}/>{React.createElement(opGlyphs[op.kind],{size:14})}<strong>{OP_LABELS[op.kind]}</strong><DropdownMenu><DropdownMenuTrigger asChild><button aria-label={'Actions for '+OP_LABELS[op.kind]}><MoreHorizontal size={15}/></button></DropdownMenuTrigger><DropdownMenuContent className="ps"><DropdownMenuItem disabled={!mutable||index===0} onClick={()=>{const list=[...enabledOps];[list[index-1],list[index]]=[list[index],list[index-1]];update(node.id,{operations:list})}}>Move up</DropdownMenuItem><DropdownMenuItem disabled={!mutable||index===enabledOps.length-1} onClick={()=>{const list=[...enabledOps];[list[index+1],list[index]]=[list[index],list[index+1]];update(node.id,{operations:list})}}>Move down</DropdownMenuItem><DropdownMenuItem disabled={!mutable} onClick={()=>update(node.id,{operations:enabledOps.filter(o=>o.id!==op.id)})}>Remove tool</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>
        {op.enabled&&<div className="ng-operation-body">{op.kind==='grade'&&(['brightness','contrast','saturation'] as const).map(key=><div className="ng-range" key={key}><div className="ng-range-label"><span>{key.charAt(0).toUpperCase()+key.slice(1)}</span><output>{String(op.values[key]??100)}%</output></div><Slider aria-label={'Node '+key} value={[Number(op.values[key]??100)]} min={0} max={200} step={1} onValueChange={v=>opUpdate(op.id,{[key]:v[0]})}/></div>)}
         {op.kind==='transform'&&<><div className="ng-range"><div className="ng-range-label"><span>Scale</span><output>{String(op.values.scale??100)}%</output></div><Slider aria-label="Node scale" value={[Number(op.values.scale??100)]} min={10} max={200} onValueChange={v=>opUpdate(op.id,{scale:v[0]})}/></div><div className="ng-range"><div className="ng-range-label"><span>Rotation</span><output>{String(op.values.rotation??0)}°</output></div><Slider aria-label="Node rotation" value={[Number(op.values.rotation??0)]} min={-180} max={180} onValueChange={v=>opUpdate(op.id,{rotation:v[0]})}/></div><label className="ng-checkbox"><Checkbox checked={!!op.values.flip} onCheckedChange={v=>opUpdate(op.id,{flip:!!v})}/>Flip horizontally</label></>}
         {op.kind==='mask'&&<><Pick label="Mask shape" value={String(op.values.shape||'ellipse')} options={[{value:'ellipse',label:'Ellipse'},{value:'rectangle',label:'Rectangle'}]} onChange={v=>opUpdate(op.id,{shape:v})}/><div className="ng-range"><div className="ng-range-label"><span>Size</span><output>{String(op.values.size??80)}%</output></div><Slider aria-label="Mask size" value={[Number(op.values.size??80)]} min={5} max={100} onValueChange={v=>opUpdate(op.id,{size:v[0]})}/></div><label className="ng-checkbox"><Checkbox checked={!!op.values.invert} onCheckedChange={v=>opUpdate(op.id,{invert:!!v})}/>Invert mask</label></>}
         {op.kind==='mix'&&<><Pick label="Blend mode" value={String(op.values.blend||'source-over')} options={[{value:'source-over',label:'Normal'},{value:'multiply',label:'Multiply'},{value:'screen',label:'Screen'},{value:'overlay',label:'Overlay'},{value:'difference',label:'Difference'}]} onChange={v=>opUpdate(op.id,{blend:v})}/><div className="ng-range"><div className="ng-range-label"><span>Foreground opacity</span><output>{String(op.values.opacity??50)}%</output></div><Slider aria-label="Composite opacity" value={[Number(op.values.opacity??50)]} min={0} max={100} onValueChange={v=>opUpdate(op.id,{opacity:v[0]})}/></div>{inputNodes.length<2&&<p className="ng-inline-note">Connect two image inputs. Input 1 is the background; Input 2 is the foreground.</p>}</>}
         {op.kind==='direction'&&<textarea aria-label="Tool direction note" value={String(op.values.note||'')} maxLength={5000} onChange={e=>opUpdate(op.id,{note:e.target.value})} placeholder="Notes for the next department…"/>}
        </div>}
       </div>)}
       <DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" className="ng-add-tool" disabled={!mutable}><Plus size={14}/>Add a tool<ChevronDown size={14}/></Button></DropdownMenuTrigger><DropdownMenuContent className="ps">{(Object.keys(OP_LABELS) as NodeOperation['kind'][]).map(kind=><DropdownMenuItem key={kind} onClick={()=>addOp(kind)}>{OP_LABELS[kind]}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>
       {enabledOps.some(o=>o.kind!=='direction')&&<p className="ng-inline-note">Image tools render stills up to 2048 px. Video and audio are previewed as source media.</p>}
      </fieldset></>}
      {tab==='inputs'&&<fieldset disabled={!mutable} className="ng-fieldset"><div className="ng-section-title"><span>SOURCE MEDIA</span></div><Pick label="Node source asset" value={node.assetId||'none'} options={[{value:'none',label:'Use connected input'},...assets.map(a=>({value:a.id,label:a.name}))]} onChange={v=>update(node.id,{assetId:v==='none'?undefined:v})}/>{node.type==='switch'&&<p className="ng-inline-note">Switch nodes use the chosen connection as their source.</p>}<div className="ng-section-title"><span>CONNECTED INPUTS</span><span>{inputNodes.length}</span></div>{inputNodes.map((n,i)=><div className="ng-input-row" key={n.id}><span className="ng-input-number">{String(i+1).padStart(2,'0')}</span><button className="ng-input-name" onClick={()=>onSelect(n.id)}><strong>{n.title}</strong><small>{NODE_DEFS[n.type].label}{node.type==='merge'?(i===0?' · Background':i===1?' · Foreground':' · Reference'):''}</small></button><Tool label={'Move '+n.title+' earlier'} disabled={i===0||!mutable} onClick={()=>{const linked=[...node.linked];[linked[i-1],linked[i]]=[linked[i],linked[i-1]];update(node.id,{linked})}}><ArrowUp size={13}/></Tool><Tool label={'Disconnect '+n.title} disabled={!mutable} onClick={()=>update(node.id,{linked:node.linked.filter(id=>id!==n.id),activeInput:node.activeInput===n.id?undefined:node.activeInput})}><X size={14}/></Tool></div>)}<Pick label="Add node input" value="choose" options={[{value:'choose',label:'Connect an existing node…'},...nodes.filter(n=>!canConnect(nodes,n.id,node.id)).map(n=>({value:n.id,label:n.title}))]} onChange={v=>{if(v!=='choose')connect(v,node.id)}}/><p className="ng-inline-note">Outputs can feed several nodes. Drag between ports, or choose an input here.</p><div className="ng-section-title"><span>USED BY</span></div>{nodes.filter(n=>n.linked.includes(node.id)).map(n=><button className="ng-used-by" key={n.id} onClick={()=>onSelect(n.id)}><GitBranch size={14}/>{n.title}<ArrowUpRight size={13}/></button>)}</fieldset>}
      {tab==='versions'&&<div className="ng-versions"><p>Save the source, direction and tool stack as a version you can return to.</p><div className="ng-save-version"><input aria-label="Version name" placeholder="Version name (optional)" value={versionName} maxLength={200} onChange={e=>setVersionName(e.target.value)} disabled={!mutable}/><Button className="btn" variant="outline" disabled={!mutable} onClick={snapshot}><Plus size={14}/>Save version</Button></div>{[...(node.versions||[])].reverse().map(v=><div className="ng-version" key={v.id}><span><GitBranch size={16}/></span><div><strong>{v.label}</strong><small>{new Date(v.savedAt).toLocaleDateString('en-GB',{day:'2-digit',month:'short'})} · {v.operations.length} tools</small></div><button disabled={!mutable} onClick={()=>{const current={id:uid('version'),label:'Before restoring '+v.label,assetId:node.assetId,text:node.text,operations:structuredClone(operationsFor(node)),savedAt:new Date().toISOString()};update(node.id,{assetId:v.assetId,text:v.text,operations:structuredClone(v.operations),versions:[...(node.versions||[]),current].slice(-30)});toast.success(v.label+' restored')}}>Restore</button></div>)}{!node.versions?.length&&<div className="ng-version-empty"><GitBranch size={24}/><span>No saved versions yet.</span></div>}</div>}
     </div>
     <div className="ng-inspector-actions">{visual?<><Button className="btn primary full-width" disabled={saving||!mutable} onClick={()=>void saveImage()}>{saving?<Settings2 size={15} className="spin"/>:<Layers size={15}/>}Save rendered take</Button><div><button disabled={saving} onClick={()=>void saveImage(true)}><Download size={14}/>PNG</button><button disabled={readonly} onClick={()=>showAsset(asset!.id)}><ArrowUpRight size={14}/>Source</button><button disabled={readonly} onClick={()=>{if(hasImageTools(node,nodes)){toast('Save a rendered take first, then add that take to the sequence.');return;}onSequence(asset!)}}><Film size={14}/>Sequence</button></div></>:<Button className="btn primary full-width" disabled={readonly} onClick={()=>node.type==='output'?onDeliver():openCrew()}>{node.type==='output'?<Download size={15}/>:<Sparkles size={15}/>} {node.type==='output'?'Open delivery':'Open production crew'}</Button>}</div>
    </>:<div className="ng-inspector-empty"><MousePointer2 size={28}/><h3>Every detail, in one place.</h3><p>Select a node to adjust its tools, connect inputs and manage versions.</p></div>}</aside></MobilePanel>
  </div>
 </div>;
}
