import {test,expect} from '@playwright/test';
import {mkdtempSync} from 'node:fs';
import path from 'node:path';
import {tmpdir} from 'node:os';
import type {TenantWorkspace} from '../../lib/tenant';
const directory=mkdtempSync(path.join(tmpdir(),'platform-spend-funding-'));
process.env.PLATFORM_DATABASE_URL=`file:${path.join(directory,'platform.db')}`;
process.env.TURSO_DATABASE_URL=`file:${path.join(directory,'tenant.db')}`;
process.env.KEYRING_SECRET??='unit-test-keyring-secret-unit-test-keyring';
const workspace=(name:string,keys:Record<string,string>={}):TenantWorkspace=>({id:`ws_${name}`,slug:name,name,legacy:false,dbUrl:`file:${path.join(directory,`${name}.db`)}`,dbToken:null,keys,usesPlatformKeys:true,allowanceUsd:null,gatewayKeyId:null,ownerId:'u_test',createdAt:0,suspendedAt:null,suspendedReason:null,flaggedAt:null,flagNote:null,concurrency:null,rendersPerHour:null,storageQuotaBytes:null,deletedAt:null});
async function scope(name:string,run:(ws:TenantWorkspace)=>Promise<void>,keys:Record<string,string>={}){const {runInTenant}=await import('../../lib/tenant');const {ready}=await import('../../lib/db');const {platformReady}=await import('../../lib/platform');const ws=workspace(name,keys);await runInTenant(ws,async()=>{await ready();await platformReady();await run(ws);});}
async function spent(id:string,cost:number){const {db}=await import('../../lib/db');await db().execute({sql:'INSERT INTO atomik_spend(id,model,cost_usd,created_at) VALUES(?,?,?,100)',args:[id,'openai/gpt-6-astra',cost]});}
async function metered(ws:string,id:string,cost:number,paid:boolean,at=100,engine='openai'){const {platformDb}=await import('../../lib/platform');await platformDb().execute({sql:"INSERT INTO meter_events(id,workspace_id,kind,engine,model,status,engine_cost_usd,paid_by_platform,created_at,updated_at) VALUES(?,?,'text',?,'openai/gpt-6-astra','succeeded',?,?,?,?)",args:[id,ws,engine,cost,paid?1:0,at,at]});}
test('adding an OpenAI key never reclassifies pre-meter Gateway text history',async()=>scope('legacy-gateway',async ws=>{const {platformSpendRecordsSince,platformSpendSince}=await import('../../lib/platformSpend');await spent('historical-gateway',1.5);expect((await platformSpendRecordsSince(0)).get('historical-gateway')).toBe(1.5);ws.keys.openai='workspace-key-added-later';expect((await platformSpendRecordsSince(0)).get('historical-gateway')).toBe(1.5);expect(await platformSpendSince(0)).toBe(1.5);}));
test('meter funded flags override mixed Gateway history, direct platform cost and direct BYOK cost',async()=>scope('mixed',async ws=>{const {platformSpendSince}=await import('../../lib/platformSpend');await spent('old-gateway',2);await spent('direct-byok',8);await spent('direct-platform',7);await metered(ws.id,'direct-byok',8,false);await metered(ws.id,'direct-platform',0.75,true);await metered(ws.id,'native-compute',0.02,true,100,'vercel-sandbox');expect(await platformSpendSince(0)).toBeCloseTo(2.77);ws.keys.openai='new-own-key';expect(await platformSpendSince(0)).toBeCloseTo(2.77);}));
test('all-media-BYOK workspaces still count funded text/compute and isolate workspace/date boundaries',async()=>scope('all-byok',async ws=>{const {platformSpendSince}=await import('../../lib/platformSpend');await metered(ws.id,'funded-before-key-rotation',3,true);await metered(ws.id,'owned-after-key-rotation',20,false);await metered(ws.id,'older-billing-window',40,true,1);await metered('another-workspace','other-tenant',100,true);expect(await platformSpendSince(50)).toBe(3);delete ws.keys.openai;expect(await platformSpendSince(50)).toBe(3);},{ark:'own',gemini:'own',gateway:'own',fal:'own',elevenlabs:'own',higgsfield:'own',openai:'own'}));
test('a corrected terminal meter cost replaces the estimate rather than double-counting it',async()=>scope('settled',async ws=>{const {platformSpendSince}=await import('../../lib/platformSpend');const {platformDb}=await import('../../lib/platform');await spent('settled-attempt',5);await metered(ws.id,'settled-attempt',2,true);expect(await platformSpendSince(0)).toBe(2);await platformDb().execute("UPDATE meter_events SET engine_cost_usd=0,paid_by_platform=0 WHERE id='settled-attempt'");expect(await platformSpendSince(0)).toBe(0);}));
